name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ros_distribution: [jazzy]
    steps:
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: Build and test
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: rabcl
          target-ros2-distro: ${{ matrix.ros_distribution }}
          colcon-defaults: |
            {
              "build": {
                "mixin": ["coverage-gcc"]
              }
            }
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml

      - name: Upload test logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: colcon-logs-${{ matrix.ros_distribution }}
          path: ros_ws/log
